name: Update Property Dispatch Listener Workflow

run-name: 'Update Property Dispatch Listener -- ${{github.event.client_payload.artifactID}} ${{github.event.client_payload.version}}'

# Pipeline/Workflow Triggers
on:
    repository_dispatch:
      types:
        - tinkar-trigger

jobs:
    update-job:
        name: Update Version Property
        runs-on: ubuntu-24.04
        if: github.event_name == 'repository_dispatch' && github.repository_owner == 'ikmdev'
        steps:  
        - name: Checkout Repository
          uses: actions/checkout@v4
          with:
            token: ${{secrets.IKMDEVOPS_PAT_TOKEN}}

        - name: "Update ${{github.event.client_payload.artifactID}} Version Property"
          run: |
            find . -name "pom.xml" -exec \
            mvn versions:set-property -Dproperty=${{github.event.client_payload.artifactID}}.version -DnewVersion=${{github.event.client_payload.version}} \
            -f {} \;

        - name: Push to Default branch
          run: |
            git config user.name "ikmdevops"
            git config user.email "devops@ikm.dev"
            git pull -p
            git add .
            git commit -m"Changed ${{github.event.client_payload.artifactID}} version to ${{github.event.client_payload.version}}"
            git push
          

